rules:
  well.all:
    schedule: "* * * * *"
    object_type: WELL
    config:
      load_deltas: True
  wellbore.all:
    schedule: "* * * * *"
    object_type: WELLBORE
    config:
      load_deltas: True
  trajectory.growing:
    schedule: "* * * * *"
    base_query: <trajectorys xmlns="http://www.witsml.org/schemas/1series" version="1.4.1.1"><trajectory></trajectory></trajectorys>
    object_type: TRAJECTORY
    config:
      load_deltas: True
